var headers = {
    'Host'              : 'www.jakmall.com',
    'Connection'        : 'keep-alive',
    'sec-ch-ua'         : '"Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"',
    'sec-ch-ua-mobile'  : '?0',
    'sec-ch-ua-platform': '"macOS"',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent'        : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
    'Accept'            : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Sec-Fetch-Site'    : 'same-origin',
    'Sec-Fetch-Mode'    : 'navigate',
    'Sec-Fetch-User'    : '?1',
    'Sec-Fetch-Dest'    : 'document',
    'Referer'           : 'https://www.jakmall.com/abc-store/taffware-humi-air-humidifier-ultrasonic-wood-grain-300ml-k-h98',
    'Accept-Encoding'   : 'gzip, deflate, br',
    'Accept-Language'   : 'id,id-ID;q=0.9,en;q=0.8',
    'X-Csrf-Token': csrfToken,
    'X-Requested-With': 'XMLHttpRequest' // Tambahkan header ini
};

headers: {
    'Host'              : 'www.jakmall.com',
    'Connection'        : 'keep-alive',
    'sec-ch-ua'         : '"Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"',
    'sec-ch-ua-mobile'  : '?0',
    'sec-ch-ua-platform': '"macOS"',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent'        : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
    'Accept'            : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Sec-Fetch-Site'    : 'same-origin',
    'Sec-Fetch-Mode'    : 'navigate',
    'Sec-Fetch-User'    : '?1',
    'Sec-Fetch-Dest'    : 'document',
    'Referer'           : 'https://www.jakmall.com/abc-store/taffware-humi-air-humidifier-ultrasonic-wood-grain-300ml-k-h98',
    'Accept-Encoding'   : 'gzip, deflate, br',
    'Accept-Language'   : 'id,id-ID;q=0.9,en;q=0.8',
    'X-Requested-With': 'XMLHttpRequest' // Tambahkan header ini
  },